### ISSUE TITLE
Library not working?

### ISSUE THREAD

**Issue by BleuLlama** [Tch1b0/itchio-lib#6] opened 2022-07-14 02:30 UTC
I just used pip3 to install itchio-lib, and it seems to have installed fine.
However, when i try to use it, or run the test.py included with the project i get these results:

` #python3 test.py` 
` Traceback (most recent call last):` 
`   File "test.py", line 2, in <module>` 
`    import itchio` 
`   File "/Users/scottl/Library/Python/3.8/lib/python/site-packages/itchio/__init__.py", line 4, in <module>` 
`     from itchio.Game import Game` 
`   File "/Users/scottl/Library/Python/3.8/lib/python/site-packages/itchio/Game.py", line 9, in <module>` 
`     class Game:` 
`   File "/Users/scottl/Library/Python/3.8/lib/python/site-packages/itchio/Game.py", line 61, in Game` 
`     def purchases(self, user: Union[str, int, User]) -> list[Purchase]:` 
` TypeError: 'type' object is not subscriptable` 

I did also have to install the 'typing' package, but i can't get anything other than these errors.  I also tried with python2, but had the same responses.

**Comment by Tch1b0** [comment] 2022-07-14 07:49
Hi @BleuLlama, thank you for reporting your issue!

In this project, I used a relatively new type system that was introduced in python 3.9 I believe.
So the issue is the return type of `purchases`, which is `list[Purchase]`. Before python 3.9 this `list` type was `List` and had to be explicitly imported from the `typing` module.

The problem should be fixed in the newest version, feel free to close this issue if it works for you or comment on it if it still doesn't work.

**Closed as completed** 2024-06-28 07:05 UTC
